<a href="https://colab.research.google.com/github/vixerica0726/exerciciosPython/blob/main/atividadePythonNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Crie um array com 4 linhas e 3 colunas com valores aleatórios.


In [3]:
import numpy as np  # Importa a biblioteca Numpy
array1 = np.random.rand(4, 3)  # Cria um array com valores aleatórios
print(array1)

[[0.39789655 0.95594889 0.34377975]
 [0.54401196 0.10570895 0.43636826]
 [0.39504392 0.00830448 0.09070987]
 [0.67768655 0.42429292 0.36039074]]


2. Crie um array com valores inteiros, 3 linhas e 5 colunas com valores
aleatórios

In [4]:
array2 = np.random.randint(1, 100, (3, 5))  # Cria um array com inteiros entre 1 e 100
print(array2)  # Imprime o array gerado


[[56 81 62 56 29]
 [22 87 14 52 24]
 [57 28 52 50 30]]


3. Crie um array com 5 colunas e 10 linhas inicializados com zeros.



In [6]:
# Cria um array com 10 linhas e 5 colunas, preenchido com zeros
array = np.zeros((10, 5))
print(array)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


4. 4. Crie um array que vá entre 0 e 90 pulando de 4 em 4.


In [7]:
array = np.arange(0, 91, 4)
print(array)


[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88]


5. Reduza o array (5,7) a apenas uma dimensão.


In [8]:
array = np.random.randint(1, 10, size=(5, 7))  # Cria um array 5x7 com valores aleatórios entre 1 e 10
array_reduzido = array.flatten()  # Reduz para uma única dimensão

print(array_reduzido)


[6 6 6 1 5 2 1 5 9 2 2 9 2 3 2 8 8 6 9 9 6 4 3 4 9 1 6 6 3 7 8 3 9 4 5]


6. Considerando que você é uma organizadora de um jogo de bingo. Crie
um array que irá representar a cartilha desses jogos de bingo. os
números das suas cartelas variam entre 1 e 30, e você terá 10
participantes. Cada cartela terá 12 números (4, 3). Crie um array que
representa esse jogo.


In [9]:
array_bingo = np.random.randint(1, 31, size=(10, 4, 3))  # Cria um array 10x4x3 com números entre 1 e 30

print(array_bingo)


[[[10  2  2]
  [18 27 18]
  [26 24 27]
  [23 10 26]]

 [[18  5 22]
  [14 29 23]
  [22  9  3]
  [27 17 22]]

 [[27 24 15]
  [18 15  3]
  [ 8 16 28]
  [16 22  7]]

 [[28 19 28]
  [30 24 18]
  [26 11 18]
  [10 14 18]]

 [[ 9 25 17]
  [19 28 24]
  [25 30 27]
  [12 30  3]]

 [[27  6 13]
  [ 8 22  7]
  [ 6 24 27]
  [14 17  2]]

 [[28 10 21]
  [ 4  9  1]
  [30  2  3]
  [19 19 19]]

 [[16  1 22]
  [30  8 23]
  [29 18 13]
  [ 2  1 21]]

 [[19  1 25]
  [ 1 22 16]
  [13 14  7]
  [22 29 27]]

 [[15  9  5]
  [11 19 28]
  [ 4  9  8]
  [ 5 11 12]]]


7. Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e
6 colunas.

In [10]:
array_bingo_reshape = array_bingo.reshape(5, 4, 6)  # Altera o formato para 5 cartelas com 4 linhas e 6 colunas

print(array_bingo_reshape)


[[[10  2  2 18 27 18]
  [26 24 27 23 10 26]
  [18  5 22 14 29 23]
  [22  9  3 27 17 22]]

 [[27 24 15 18 15  3]
  [ 8 16 28 16 22  7]
  [28 19 28 30 24 18]
  [26 11 18 10 14 18]]

 [[ 9 25 17 19 28 24]
  [25 30 27 12 30  3]
  [27  6 13  8 22  7]
  [ 6 24 27 14 17  2]]

 [[28 10 21  4  9  1]
  [30  2  3 19 19 19]
  [16  1 22 30  8 23]
  [29 18 13  2  1 21]]

 [[19  1 25  1 22 16]
  [13 14  7 22 29 27]
  [15  9  5 11 19 28]
  [ 4  9  8  5 11 12]]]


# Manipulando Arrays

2. Ainda usando o Array de espécies marítima

In [16]:
import numpy as np

# Dados das espécies
especies = np.array([[747, 89, 33, 5],
                     [623, 123, 32, 13],
                     [501, 22, 49, 2],
                     [116, 101, 42, 10],
                     [297, 56, 69, 22],
                     [613, 64, 27, 7],
                     [295, 84, 29, 14],
                     [692, 105, 72, 16],
                     [229, 103, 35, 5],
                     [374, 124, 70, 1]])

qtd_especies = especies[:, 1]  # Seleciona a segunda coluna (quantidade de representantes encontrados)
print("Segunda coluna de quantidade de espécies encontradas",qtd_especies)

print("3 primeiras quantidades de espécies", qtd_especies[:3])

print("5 útimas Quantidades de espécies", qtd_especies[-5:])

tamanhos = especies[:, 3]  # Seleciona a coluna de tamanhos
tamanhos_ordenados = np.sort(tamanhos)
print("Ordem crescente -> ", tamanhos_ordenados)


Segunda coluna de quantidade de espécies encontradas [ 89 123  22 101  56  64  84 105 103 124]
3 primeiras quantidades de espécies [ 89 123  22]
5 útimas Quantidades de espécies [ 64  84 105 103 124]
Ordem crescente ->  [ 1  2  5  5  7 10 13 14 16 22]


In [22]:
import numpy as np

# Dados das espécies (especies)
especies = np.array([[747, 89, 33, 5],
                     [623, 123, 32, 13],
                     [501, 22, 49, 2],
                     [116, 101, 42, 10],
                     [297, 56, 69, 22],
                     [613, 64, 27, 7],
                     [295, 84, 29, 14],
                     [692, 105, 72, 16],
                     [229, 103, 35, 5],
                     [374, 124, 70, 1]])

# a. Adicionando mais 2 espécies
novas_especies = np.array([[204, 10, 40, 12], [392, 11, 81, 11]])
especies = np.vstack([especies, novas_especies])  # Adiciona as novas espécies ao array

# b. Adicionando uma nova coluna com o número de espécies encontradas que indicam se o animal enxerga ou não
enxerga = np.array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0])  # Indica se o animal enxerga ou não
enxerga = np.resize(enxerga, (len(especies),))  # Ajusta o tamanho para corresponder ao número de linhas em 'especies'
especies = np.column_stack([especies, enxerga])  # Adiciona como nova coluna

print("\nDados das espécies após a adição de novas espécies e coluna de visão:")
print(especies)



Dados das espécies após a adição de novas espécies e coluna de visão:
[[747  89  33   5   0]
 [623 123  32  13   1]
 [501  22  49   2   0]
 [116 101  42  10   0]
 [297  56  69  22   0]
 [613  64  27   7   0]
 [295  84  29  14   1]
 [692 105  72  16   0]
 [229 103  35   5   1]
 [374 124  70   1   1]
 [204  10  40  12   0]
 [392  11  81  11   0]]


3. Ainda no conjunto 'especies'.
Cálculo com Array


In [23]:
import numpy as np

# Dados das espécies (especies)
especies = np.array([[747, 89, 33, 5],
                     [623, 123, 32, 13],
                     [501, 22, 49, 2],
                     [116, 101, 42, 10],
                     [297, 56, 69, 22],
                     [613, 64, 27, 7],
                     [295, 84, 29, 14],
                     [692, 105, 72, 16],
                     [229, 103, 35, 5],
                     [374, 124, 70, 1]])

# a. Adicionando mais 2 espécies
novas_especies = np.array([[204, 10, 40, 12], [392, 11, 81, 11]])
especies = np.vstack([especies, novas_especies])  # Adiciona as novas espécies ao array

# b. Adicionando uma nova coluna com o número de espécies encontradas que indicam se o animal enxerga ou não
enxerga = np.array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0])  # Indica se o animal enxerga ou não
enxerga = np.resize(enxerga, (len(especies),))  # Ajusta o tamanho para corresponder ao número de linhas em 'especies'
especies = np.column_stack([especies, enxerga])  # Adiciona como nova coluna

print("\nDados das espécies após a adição de novas espécies e coluna de visão:")
print(especies)

# 4. Cálculos com o array acidentes
acidentes = np.array([[1, 3, 2],
                      [0, 1, 0],
                      [2, 1, 4],
                      [0, 0, 0],
                      [1, 1, 0]])

# 1. Cliente que teve acidente abaixo da média nos últimos 2 anos
media_acidentes = acidentes.mean(axis=1)  # Média de acidentes por cliente
clientes_abaixo_media = acidentes[acidentes.mean(axis=1) < media_acidentes]  # Clientes com acidentes abaixo da média

print("\nClientes com acidente abaixo da média nos últimos 2 anos:")
print(clientes_abaixo_media)

# 2. Qual cliente teve pelo menos 2 anos sem cometer acidentes?
clientes_sem_acidente = np.where((acidentes == 0).sum(axis=1) >= 2)  # Verifica os clientes com 2 ou mais anos sem acidentes
print("\nCliente(s) que teve pelo menos 2 anos sem cometer acidentes:")
print(acidentes[clientes_sem_acidente])

# 3. Aplicando a função (3x + 2y + x * y) nos dados
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
resultado = 3 * x + 2 * y + x * y  # Aplica a fórmula fornecida
print("\nResultado da função (3x + 2y + x * y):")
print(resultado)

# 4. Adicionando a mesma nota para todos os estudantes
notas_trabalho = np.array([1, 2, 1])
notas_trabalho_expandida = np.tile(notas_trabalho, (acidentes.shape[0], 1))  # Expande as notas para todas as provas
print("\nNotas das provas após adicionar as notas de trabalho para todos os estudantes:")
print(notas_trabalho_expandida)



Dados das espécies após a adição de novas espécies e coluna de visão:
[[747  89  33   5   0]
 [623 123  32  13   1]
 [501  22  49   2   0]
 [116 101  42  10   0]
 [297  56  69  22   0]
 [613  64  27   7   0]
 [295  84  29  14   1]
 [692 105  72  16   0]
 [229 103  35   5   1]
 [374 124  70   1   1]
 [204  10  40  12   0]
 [392  11  81  11   0]]

Clientes com acidente abaixo da média nos últimos 2 anos:
[]

Cliente(s) que teve pelo menos 2 anos sem cometer acidentes:
[[0 1 0]
 [0 0 0]]

Resultado da função (3x + 2y + x * y):
[15 26 39]

Notas das provas após adicionar as notas de trabalho para todos os estudantes:
[[1 2 1]
 [1 2 1]
 [1 2 1]
 [1 2 1]
 [1 2 1]]
